######################################################################
# Automatically generated by qmake (2.01a) Mo 9. Feb 19:34:22 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

QT += sql

# Input
HEADERS += src/BerichteOrk.h src/DataHandler.h
FORMS += src/mainwindow.ui
SOURCES += src/BerichteOrk.cpp src/DataHandler.cpp src/main.cpp
RESOURCES += src/resources.qrc
